'use client';

import { useState } from 'react';
import Navbar from '@/components/Navbar';
import { submissions } from '@/lib/demoData';
import { Sparkles, AlertCircle } from 'lucide-react';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

export default function AdminPage() {
  const [activeFilter, setActiveFilter] = useState('All');
  
  // Compute stats
  const totalSubmissions = submissions.length;
  const openIssues = submissions.filter(s => s.status === 'Open').length;
  const safetyFlags = submissions.filter(s => s.safety_flag === true).length;
  const averageUrgency = (
    submissions.reduce((sum, s) => sum + s.urgency, 0) / submissions.length
  ).toFixed(1);

  const stats = [
    { label: 'Total Submissions', value: totalSubmissions },
    { label: 'Open Issues', value: openIssues },
    { label: 'Safety Flags', value: safetyFlags },
    { label: 'Average Urgency', value: averageUrgency }
  ];

  const categories = ['All', 'Academic', 'Facilities', 'Conduct', 'Safety', 'Other'];

  // Filter and sort submissions
  const filteredSubmissions = (
    activeFilter === 'All'
      ? submissions
      : submissions.filter(s => s.category === activeFilter)
  ).sort((a, b) => b.urgency - a.urgency);

  // Category badge colors
  const categoryColors = {
    Academic: 'bg-blue-100 text-blue-800',
    Facilities: 'bg-orange-100 text-orange-800',
    Conduct: 'bg-purple-100 text-purple-800',
    Safety: 'bg-red-100 text-red-800',
    Other: 'bg-gray-100 text-gray-800'
  };

  // Urgency dot and color
  const getUrgencyColor = (urgency) => {
    if (urgency <= 4) return 'text-green-500';
    if (urgency <= 7) return 'text-amber-500';
    return 'text-red-500';
  };

  // Chart data - submissions per category
  const categoryData = [
    { name: 'Academic', count: submissions.filter(s => s.category === 'Academic').length },
    { name: 'Facilities', count: submissions.filter(s => s.category === 'Facilities').length },
    { name: 'Conduct', count: submissions.filter(s => s.category === 'Conduct').length },
    { name: 'Safety', count: submissions.filter(s => s.category === 'Safety').length },
    { name: 'Other', count: submissions.filter(s => s.category === 'Other').length }
  ];

  // Chart data - submission volume by week
  const weeklyData = [
    { week: 'Week 1', submissions: 3 },
    { week: 'Week 2', submissions: 3 },
    { week: 'Week 3', submissions: 3 },
    { week: 'Week 4', submissions: 3 }
  ];

  return (
    <>
      <Navbar />
      
      <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <h1 className="text-3xl font-bold text-gray-900 mb-8">Admin Dashboard</h1>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {stats.map((stat, index) => (
              <div key={index} className="bg-white rounded-lg shadow-sm p-6">
                <p className="text-sm text-gray-600 mb-2">{stat.label}</p>
                <p className="text-4xl font-bold text-brand">{stat.value}</p>
              </div>
            ))}
          </div>

          <div className="mt-8 bg-lightgreen rounded-lg p-6">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles className="w-5 h-5 text-brand" />
              <h2 className="text-lg font-bold text-gray-900">AI Weekly Digest</h2>
            </div>
            <p className="text-gray-700 mb-4">
              This week's top concern is classroom overcrowding in the Engineering block, reported across 6 separate submissions. Two safety-related issues require immediate attention from Security. Conduct complaints have increased 40% compared to last week.
            </p>
            <p className="text-sm text-gray-600">
              Generated by AI — updated every Monday
            </p>
          </div>

          {/* Filter Bar */}
          <div className="mt-8 flex flex-wrap gap-2">
            {categories.map((category) => (
              <button
                key={category}
                onClick={() => setActiveFilter(category)}
                className={`px-4 py-2 rounded-full font-medium transition-colors ${
                  activeFilter === category
                    ? 'bg-brand text-white'
                    : 'bg-white text-gray-700 hover:bg-gray-100'
                }`}
              >
                {category}
              </button>
            ))}
          </div>

          {/* Issue Feed */}
          <div className="mt-8 space-y-4">
            {filteredSubmissions.map((submission) => (
              <div key={submission.id} className="bg-white rounded-lg shadow-sm p-6">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <span className={`px-3 py-1 rounded-full text-sm font-medium ${categoryColors[submission.category]}`}>
                      {submission.category}
                    </span>
                    {submission.safety_flag && (
                      <span className="px-3 py-1 rounded-full text-sm font-medium bg-red-100 text-red-800 flex items-center gap-1">
                        <AlertCircle className="w-4 h-4" />
                        Safety Alert
                      </span>
                    )}
                  </div>
                  <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                    submission.status === 'Open'
                      ? 'bg-amber-100 text-amber-800'
                      : 'bg-green-100 text-green-800'
                  }`}>
                    {submission.status}
                  </span>
                </div>

                <p className="text-gray-700 mb-3">{submission.summary}</p>

                <div className="flex items-center justify-between text-sm text-gray-600">
                  <div className="flex items-center gap-2">
                    <span className={`w-3 h-3 rounded-full ${getUrgencyColor(submission.urgency)}`} />
                    <span>Urgency: {submission.urgency}</span>
                  </div>
                  <span>{submission.date}</span>
                </div>
              </div>
            ))}
          </div>

          {/* Trends Section */}
          <div className="mt-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-8">Trends this month</h2>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              {/* Category Bar Chart */}
              <div className="bg-white rounded-lg shadow-sm p-6">
                <h3 className="text-lg font-bold text-gray-900 mb-4">Submissions by Category</h3>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={categoryData}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="name" />
                    <YAxis />
                    <Tooltip />
                    <Bar dataKey="count" fill="#2D6A4F" />
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Weekly Line Chart */}
              <div className="bg-white rounded-lg shadow-sm p-6">
                <h3 className="text-lg font-bold text-gray-900 mb-4">Submission Volume by Week</h3>
                <ResponsiveContainer width="100%" height={300}>
                  <LineChart data={weeklyData}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="week" />
                    <YAxis />
                    <Tooltip />
                    <Line type="monotone" dataKey="submissions" stroke="#2D6A4F" strokeWidth={2} dot={{ fill: '#2D6A4F' }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
